/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EssaysIndexRouteImport } from './routes/essays.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as EssaysSlugRouteImport } from './routes/essays.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysIndexRoute = EssaysIndexRouteImport.update({
  id: '/essays/',
  path: '/essays/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaysSlugRoute = EssaysSlugRouteImport.update({
  id: '/essays/$slug',
  path: '/essays/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/essays': typeof EssaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/essays/$slug': typeof EssaysSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/essays/': typeof EssaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/essays/$slug' | '/work/$slug' | '/essays/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/essays/$slug' | '/work/$slug' | '/essays'
  id: '__root__' | '/' | '/essays/$slug' | '/work/$slug' | '/essays/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EssaysSlugRoute: typeof EssaysSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  EssaysIndexRoute: typeof EssaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/': {
      id: '/essays/'
      path: '/essays'
      fullPath: '/essays/'
      preLoaderRoute: typeof EssaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essays/$slug': {
      id: '/essays/$slug'
      path: '/essays/$slug'
      fullPath: '/essays/$slug'
      preLoaderRoute: typeof EssaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EssaysSlugRoute: EssaysSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  EssaysIndexRoute: EssaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
